# Generated by Django 5.1.7 on 2025-05-11 06:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='profile_pozuuv', max_length=255, null=True, verbose_name='image'),
        ),
    ]
