# Generated by Django 5.1.7 on 2025-05-15 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_bio_remove_user_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileinfo',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='profileinfo',
            name='profession',
        ),
        migrations.AddField(
            model_name='user',
            name='institute',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
