# Generated by Django 5.1.7 on 2025-05-15 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_profileinfo_institute_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileinfo',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profileinfo',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='profileinfo',
            name='qualifications',
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.CharField(blank=True, default='Student', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='qualifications',
            field=models.TextField(blank=True, null=True),
        ),
    ]
