# Generated by Django 5.1.7 on 2025-05-15 02:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_profileinfo_bio_remove_profileinfo_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='profile_pozuuv', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.DeleteModel(
            name='ProfileInfo',
        ),
    ]
