# Generated by Django 5.1.7 on 2025-05-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tran_id',
            field=models.CharField(max_length=100),
        ),
    ]
