# Generated by Django 5.1.7 on 2025-05-21 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_alter_tuition_image'),
        ('users', '0014_payment_status_alter_payment_tran_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='tuition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.tuition'),
        ),
    ]
