# Generated by Django 5.1.7 on 2025-05-10 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topics_for_this_week', models.CharField(max_length=200)),
                ('topics', models.CharField(choices=[('Started', 'Started'), ('25% Completed', '25% Completed'), ('50% Completed', '50% Completed'), ('75% Completed', '75% Completed'), ('100% Completed', '100% Completed')], default='Started', max_length=15)),
                ('assignment', models.CharField(default='Coming Soon', max_length=150)),
                ('topics_completed', models.PositiveIntegerField(default=0)),
                ('student_progress', models.CharField(choices=[('Doing Well', 'Doing Well'), ('Need More Hardwork', 'Need More Hardwork'), ('Greate', 'Greate'), ('Not So Well', 'Not So Well')], default='Doing Well', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='StudentsOfTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tuition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('classes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('subjects', models.CharField(max_length=150)),
                ('availability', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=5)),
                ('Enrolled', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
