# Generated by Django 5.1.7 on 2025-05-10 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='progress',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentsofteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentOfTeacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentsofteacher',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tuition',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuition', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentsofteacher',
            name='tuition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='teachers.tuition'),
        ),
        migrations.AddField(
            model_name='review',
            name='tuition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='teachers.tuition'),
        ),
        migrations.AddField(
            model_name='progress',
            name='tuition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='teachers.tuition'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='tuition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to='teachers.tuition'),
        ),
    ]
