# Generated by Django 5.1.7 on 2025-05-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuition',
            name='course_content',
            field=models.TextField(default='My Course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tuition',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tuition',
            name='fee',
            field=models.PositiveBigIntegerField(default=499),
        ),
        migrations.AddField(
            model_name='tuition',
            name='outcomes',
            field=models.TextField(default='My outcome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tuition',
            name='sub_title',
            field=models.CharField(default='my sub_title', max_length=150),
            preserve_default=False,
        ),
    ]
