# Generated by Django 5.1.7 on 2025-05-10 15:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_tuition_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuition',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
